name: Build docker and push image in AWS ECR
on: 
  push:
    branches: [main]
jobs:
 build-and-push:
   name: build and push to ecr
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@version2

   - name: Configure Aws Credentials
     uses: aws-action/configure-aws-credentials@v1
     with:
       aws-ACCESS-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-acces-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1
       
   - name: Login to amazon ECR
     id: login-ecr
     uses: aws-actions/amazon-ecr-login@v1

   - name: Buid tag and push the image to amazon ECR
     id: build-image
     env:
       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
       ECR_REPOSITORY: app1
       IMAGE_TAG: latest
   run: |
     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG app1/.
   - name: Buid tag and push the image to amazon ECR 2
     id: build-image
     env:
       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
       ECR_REPOSITORY: app2
       IMAGE_TAG: latest
   run: |
     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG app2/.
