name: Infraestructura deploy


on: 
  push: 
    branches: [ "main" ]



jobs:
  build:
    name: terraform settings
    runs-on: ubuntu-latest
    steps:
    - name: check repo
      uses: actions/checkout@v3
    - name: Terraform version
      run: terraform version
